### PR TITLE
Add Python3 Support

### PR DESCRIPTION
**Pull request by earthpyy**
# Changes
- Add Python 3.5+ support
- Update Python dependencies
- Rebuild gRPC

### CODE REVIEW

**Comment by earthpyy** [comment]
@dcramer 

Hello,
If you have time, could you please review this change for me?

Thanks very much!

**Comment by dcramer** [comment]
Seems straight forward - what was the approach to build the bindings so that they supported both?

**Comment by earthpyy** [comment]
Hello,

First of all, thanks for the quick response! Actually, I did nothing. Seems like the gRPC was built to support both versions. I already tested in Python 2.7.18 and 3.9.1. It looks fine so far.

Here's the screenshot for both versions:

image

image

BTW, your work on Sentry is terrific! It helps me a lot! And I'm very glad to have a conversation with you.

Have a nice day!

**Comment by dcramer** [comment]
@earthpyy thanks! Glad you vetted it as I was debating how I was going to do the same without spending a lot of time :)

**Comment by dcramer** [comment]
Published 0.2.0 - pretty sure its correct for both py2/py3, tho i was disappointed in myself that I didn't setup a build script (or GitHub Action!) to auto publish previously!

**Comment by earthpyy** [comment]
Everything is fine. Very thanks to you and have a nice day!

**Pull request merged**
